### ISSUE TITLE
PyBossa now supports Twitter out of the box

### ISSUE THREAD

**Issue by teleyinex** [project-recoin/PybossaTwitterController#17]
Hi,

We've discovered that have been working on this PyBossa-Twitter integration. I'm writing here to let you know that the latest version of PyBossa is fully integrated with the API of Twitter allowing you to import tweets almost in real-time (it gets tweet using the limitations of the API of twitter).

You can read more about it [here](http://docs.pybossa.com/en/latest/user/overview.html?highlight=twitter#importing-the-tasks-from-a-twitter-account-or-search-result).

All the best,

Daniel

**Comment by m-l-r** [comment]
Hi Daniel.

Sorry for the late response. Yes, we were aware of this feature in PyPossa but what we do is slightly different from that. We do not pull tasks from social media, we push them out to social media (Twitter and facebook now) and collect task runs from people responding to those messages on these platforms. This is described here:

http://eprints.soton.ac.uk/390545/
Luczak-Roesch, Markus, Tinati, Ramine, Aljaloud, Saud, Hall, Wendy and Shadbolt, Nigel (2016) A universal socio-technical computing machine. In, 16th International Conference on Web Engineering (ICWE2016), Lugano, CH, 06 - 09 Jun 2016.
