### ISSUE TITLE
Task performer to Twitter

### ISSUE THREAD

**Issue by m-l-r** [project-recoin/PybossaTwitterController#2]
- configure mapping between task type and dedicated Twitter account (e.g. translate task -> RECOIN_Trans)
- manage task push
- manage task response pull

**Comment by SaudAljaloud** [comment]
managed task push & manage task response pull: They are created in "sociam.pybossa.twitter.Main" within the method "public Boolean sendTaskToTwitter(String taskId, String taskContent)" and "public static HashSet<String> getTimeLineAsJsons(Twitter twitter)"

This leaves the first point to be resolved.
