### ISSUE TITLE
Second and third answers on facebook and twitter are not included as task runs

### ISSUE THREAD

**Issue by m-l-r** [project-recoin/PybossaTwitterController#22]
This needs to be fixed quickly. Second replies are currently left out by the component that pulls task runs!

**Comment by SaudAljaloud** [comment]
Fixed by removing the condition of users are only allowed one taskRun per task
6e02e4431319d76c6ae2379fd69401f1d8113cce
d464f3f96345961cdaf85532568fabe732b2af2e
