### ISSUE TITLE
Observer to Task Creator

### ISSUE THREAD

**Issue by m-l-r** [project-recoin/PybossaTwitterController#4]
To begin with the observer subscribes to an Observatory RabbitMQ stream and maintains a bin for every single hashtag observed. If size(bin)==100 the observer connects the task creator to create a project to validate that this burst of activity relates to some meaningful real-world event (create project in category "project validation"). 100 tasks need to be pushed to this project in pybossa with each task requiring n=2 answers to be completed.

**Comment by SaudAljaloud** [comment]
Done By Ramine
