### ISSUE TITLE
PyBossa does not allow to publish activated projects via the API

### ISSUE THREAD

**Issue by m-l-r** [project-recoin/PybossaTwitterController#6]
https://github.com/PyBossa/pybossa/blob/master/pybossa/api/project.py

Find workaround for this that is still save.
- limit this feature to admin API key

**Comment by SaudAljaloud** [comment]
Should we also report this to the PyBossa main repo?

**Comment by m-l-r** [comment]
We can report as requirement and ask if this (avoiding active project creation via API) is a behaviour they wanted to have for security reasons. Not top priority to report though. Not now.

**Comment by m-l-r** [comment]
We get the data out of the projects even though they are not public in pybossa. So for now this is not a problem for our minimum viable product.
